### ISSUE TITLE
What's the purpose of shift/ctrl key press?

### ISSUE THREAD

**Issue by tompetko** [goodeggs/st-multi-sort#3]
Hi there. I'm wondering, what's the purpose of these special keys? Hitting another `<th>` without holding one of these keys causes, that css will be removed from already applied cols. The whole difference between holding and not holding those keys is whether the css won't or will be unset although `sort` property of table state remains untouched?

It would be great that sorting predicates will be merged when I'm holding ctrl/shift key and reset (set to single predicate) when I'm not holding one of those keys.

**Comment by dannynelson** [comment]
Hi @tompetko,

> It would be great that sorting predicates will be merged when I'm holding ctrl/shift key and reset (set to single predicate) when I'm not holding one of those keys.

You are correct that we never reset the sort back to a single predicate. This behavior is intentional. We want to convert the primary sort to a secondary sort once the user clicks another header.

For instance, if we have a table with three headers `Th1`, `Th2`, `Th3`:
- click `Th1`, click `Th3` => sort by `[Th3, Th1]` (`Th1` converted from a primary sort to a secondary sort)
- click `Th1`, shift click `Th3` => sort by `[Th1, Th3]` (`Th3` added as a secondary sort)

For more info on how this works, see:
https://github.com/goodeggs/st-multi-sort/blob/master/src/index.coffee#L77-L81
https://github.com/goodeggs/st-multi-sort/blob/master/src/index.coffee#L60-L63
https://github.com/goodeggs/st-multi-sort/blob/master/test/test.karma.coffee#L297-L360

Does that make sense?

**Comment by tompetko** [comment]
Hi @dannynelson,

Yes, it makes sence. The only flaw it has, is that the secondarily sorted collumns has no indication and thus the whole table seems to be sorted by only one collumn. It's not a good idea to remove sort classes, it's misleading, I would rather distinguish them by adding additional class for primarily sorted collumn like `st-primary-sort-ascent` - other collumns are considered to be sorted secondarily.

**Comment by dannynelson** [comment]
@tompetko yes, that is confusing. Based on your original suggestion, `st-multi-sort@1.1.1` now resets the sort predicate when clicking without ctrl/shift so that the predicate matches the sort classes.

Thank you for the feedback!
